### PR TITLE
Navigation Bar

### LINKED ISSUE #15: Menu bar - Section links

### PR DESCRIPTION
**Pull request by supsshinde**
Updated navigation bar
closes #15

### CODE REVIEW

**Comment by priyapal2000** [comment]
@supsshinde ,
Resolve Conflicts

**Comment by supsshinde** [comment]
> @supsshinde, link issue

issue linked

**Comment by supsshinde** [comment]
@priyapal2000 conflict resolved.

**Comment by supsshinde** [comment]
@priyapal2000 please merge #21 PR.

**Review by priyapal2000 — APPROVED** [review]
Done Review.

**Comment by priyapal2000** [comment]
PR is Successfully Merge.

**Pull request merged**
