### PR TITLE
14 reach me at

### LINKED ISSUE #14: Reach me at!
- [x] #11 
- [x] #12

### PR DESCRIPTION
**Pull request by shubham-8551**
Closes # 14 reach me at

### CODE REVIEW

**Comment by shubham-8551** [comment]
@supsshinde @ajayg2808 
please review PR

**Comment by shubham-8551** [comment]
Done

closes #14

**Comment by priyapal2000** [comment]
@supsshinde  
Please Merge PR.

**Comment by supsshinde** [comment]
@shubham-8551,
Why you closed user-story? PR is still open.

**Comment by supsshinde** [comment]
@shubham-8551,
Why you added @ajayg2808 as reviewer?

**Comment by shubham-8551** [comment]
@supsshinde

Hey accept pull request, all changes are done.

**Comment by ajayg2808** [comment]
> @shubham-8551,
> Why you added @ajayg2808 as reviewer? 

@shubham-8551 Why, I am a reviewer here?

**Comment by shubham-8551** [comment]
It's by default you r here

**Review by supsshinde — APPROVED** [review]

**Comment by supsshinde** [comment]
@priyapal2000 and @shubham-8551 PR accepted.

**Pull request merged**
